sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=mapstory
  - secure: RGXXoVf6r/qYq8AXUkS6U1iinHz9jmKSHyo/4kQnLpflmCLvvPWkIGL8ObICqWX4TD7+mN9LDI7Y29o7J0G1hw4Ytjoo34Y4/rkIzQcG9YWeV474ZpJYMNdcRUjmtwTC+OfsZnkgVlaQO1PT/NGzlZSfhteKwea2vw2PUKX6YJ/l/Ven6yV+vxEaMajefIAilmD0tTiqG1Sm9ctfLJ0hGqtWE/xKowyYy+u49Qrhv79sMOep5tBskMGzEltfVbu0v5htxKOhnSIYZJG0aBCaQeCzb6lyId1PDYkffKlFqtc7P47U6Ujn80rPqrunNU9CZiedU8qtZ966IgeOXdP+GzbZYGBKWsHlBZx20PkcUiIggdgLNdpKWmPMhPKUdp8hHLw7CNAHjrPAmtOQpnIWto2maBkTeMDozOS9ktRH9WGvotV9tp6xFUMuwQZGlV9rXCjABTSQEM/5i5ntOXcsHh6XenkYKgt0ba9Kdt7lksfViJVLBccljjTaveLNypVeD9T7wpRl43+WX3mx4wKnH8SfLTkLMFQfwheVHf+AeesAVYfGlwi0PCeKIGXTOAhhQsAZ19ouZ/8gfbMMdDB+dk2QZf764K/zzHZdL2YtOxJbhZZ0itVafqBghkfieXdK+ik9jA9iBenl7Z2YkWVa03+6p1qigNqzGd/TjulsltU=
  - secure: fsd7vMDSGxhiMLB+9Obh9AgyzD+1dPt2MBhB5l6Edpjds0OsZSqW0xCZAKa4PTu6FtSBS1rOD5WkW+dosCQx76bJRXWgDW+P8nGxvd6n0M7JJ2xjo52+vowYtjhzh00a9RpXeW69SIy3FR09WfrJspOT5cYNbQz/piRnb9F6WETkmwOszRVuZB1Zq02L5a2jAKYQ6E2RZU8NrPBzmHsOaQjIyCOiiHfJm9Vv5v+tFrpSHjgBFJvQ+GYMdi1wZD0Yv9cPI5Pz8FwVPPN2Tk5cOQJJHOymqd5TS2PWHPJgN7gJONbGIb/4auNMornXVEGZUoN+Gleb+0PVpAVeNsFnW5D7iWYFHJf3NKxceKBePn7WJXAwdE8jV1J1ILVEOVa/+ppBIORWH87zlSaDKW9Mk6HNNnXGvO3+4MS97eAcJueF/favIX8iKWYTGqVJO6OcCQKV8fCrTE4UtDxZv31/OJgc1FFhWfLNjX+k7hZwwjvBIMdZd6lJVx+Jq35FmIChs5Je5jy4sCdTEI8VMuiMP+P8gc07GZD57KBUJcaru2OPXBEV8ZrLP+TreZT1pis0utnwwSZ2zO+G7p3gYaflhvbHQI+2aIqWnfBegZsxC5hk3slItvHryeluqdJW5m2ICfyZDe8BHTA+zyYi/wXD7TGUJpKw2HAYxW0c4tni4BA=
  matrix:
  - QGIS_VERSION_TAG=release
  - QGIS_VERSION_TAG=master_2
  - QGIS_VERSION_TAG=master
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master
before_install:
- docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
- docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
- sleep 10
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker exec -it qgis-testing-environment sh -c "pip install paver"
script:
- docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
- docker exec -it qgis-testing-environment sh -c "echo '${PLUGIN_NAME} has no unit tests yet, please create them and add here'"
notifications:
  slack:
    secure: sFRbG/Ay992WkV7+xkiGFMnWgUSa928/74N9ImErHo3bnio4b7lne4fyD+T1VVFgpx8p2wExS0P/Jy7782L1ljMkubKpH3GE6Edymdk6/tvVwfR8ctFlMzew66W4woU8F0uhkGxJvCNS3fCPJVSTRyv/D2UcfcSWlEI80AH3n1zLXdUgTMED+4VM/MQnVU0vwKD4RgxfKJv1lULgn0ovsJPHjMpPD4mLkqq/o+LrGf0j9Z20+eEJiw30uNR+vSmB0IW7rvLmbtBqU9RDuTDsAi8CP9+eVoxIVozKf9qiuaobUDf9Ik/GItcHkNo3qa29K0yABVg5Shpqwx2VM5DkKYdRSmbzVp5WFrSsPCA5WlTe+HvHRSHIF78lUarLSqMeCAkiPnYj+SLn5Okzg2wVAqvIvXSODD2sXI5uLSwMOnlX6HFUE5UzHPjgV2fiTbCN5C5heRW2+dTe5ZhEJ3sRV5tKCmUD9qdUFVadK2IFjM0fDCqLw4IivMLNw5a8nakEIoxX/0wg1KQtNr6cAI/AFcBwm7lGA71b7suXC4Jt3hizWau3q2liuBd3EDiia1uAEO1eiKxPPREM2bLWOI45uJLFLvLcN3Jf43vQIEx/YqZKRXjLyU98TLJAXJJny+zK2ARF2fm19oPOa75nSdT23Y3FkHHHkHwnQKGM0Wlq/J8=
after_success:
- |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
        mkdir /home/travis/.ssh/
        chmod 700 /home/travis/.ssh/
        openssl aes-256-cbc -K $encrypted_14203cc7e19a_key -iv $encrypted_14203cc7e19a_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
        tar xzvf travis_secrets.tar.gz
        mv id_rsa.qgisrepoguest /home/travis/.ssh/id_rsa.qgisrepoguest
        mv ssh_config /home/travis/.ssh/config
        chmod 600 /home/travis/.ssh/id_rsa.qgisrepoguest
        chmod 600 /home/travis/.ssh/config
        export RELEASE_ZIPNAME=${PLUGIN_NAME}.zip
        echo "Uploading ${RELEASE_ZIPNAME} to QGIS Dev..."
        scp ${PLUGIN_NAME}.zip qgisrepoguest:${UPLOADS}/${RELEASE_ZIPNAME}
        export GIT_REV=$(git rev-parse --short HEAD)
        ssh qgisrepoguest "${UPDATER} update --dev --role desktop-qgis-plugin-dev --git-hash ${GIT_REV} ${RELEASE_ZIPNAME}"
    fi
